name: memories
description: A Flutter app for creating a mood board of best memories.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  photo_manager: ^3.6.4
  image_picker: ^1.1.2
  swipe_cards: ^2.0.0+1
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  sqflite: ^2.0.0+3
  path_provider: ^2.1.4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # use latest version

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg" # your icon path

flutter:
  uses-material-design: true