name: memories
description: A Flutter app for creating a mood board of best memories.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  photo_manager: ^3.6.4
  image_picker: ^1.1.2
  swipe_cards: ^2.0.0+1
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true